export interface GlossaryEntry {
  id: string;
  term: string;
  definition: string;
  example?: string;
  formula?: string;
  pronunciation?: string;
  relatedTerms?: string[];
  relatedFAQs?: string[];
  category: 'metric' | 'technical' | 'financial' | 'dl' | 'infrastructure';
}

export const glossaryData: GlossaryEntry[] = [
  // Metrics
  {
    id: 'mape',
    term: 'MAPE',
    definition: 'Mean Absolute Percentage Error - A metric that measures the average magnitude of errors in predictions as a percentage. Lower values indicate better accuracy.',
    formula: 'MAPE = (1/n) × Σ|((Actual - Predicted) / Actual)| × 100%',
    example: 'If a model predicts a 10% return but actual is 12%, the error is 16.67%.',
    pronunciation: 'may-p',
    relatedTerms: ['Accuracy', 'Error', 'Prediction'],
    relatedFAQs: ['tech-1'],
    category: 'metric',
  },
  {
    id: 'sharpe-ratio',
    term: 'Sharpe Ratio',
    definition: 'A risk-adjusted return metric that measures excess return per unit of risk. Higher values indicate better risk-adjusted performance.',
    formula: 'Sharpe Ratio = (Portfolio Return - Risk-Free Rate) / Portfolio Standard Deviation',
    example: 'A Sharpe ratio of 2.0 means the portfolio generates 2% excess return for each 1% of risk.',
    pronunciation: 'sharp ray-shee-oh',
    relatedTerms: ['Sortino Ratio', 'Alpha', 'Beta'],
    relatedFAQs: ['tech-1'],
    category: 'metric',
  },
  {
    id: 'alpha',
    term: 'Alpha',
    definition: 'The excess return of an investment relative to a benchmark index. Positive alpha indicates outperformance.',
    formula: 'Alpha = Portfolio Return - (Risk-Free Rate + Beta × (Market Return - Risk-Free Rate))',
    example: 'An alpha of 2% means the portfolio outperformed the benchmark by 2%.',
    relatedTerms: ['Beta', 'Sharpe Ratio', 'Benchmark'],
    category: 'metric',
  },
  {
    id: 'beta',
    term: 'Beta',
    definition: 'A measure of volatility relative to the market. Beta of 1 means the asset moves with the market, >1 means more volatile, <1 means less volatile.',
    formula: 'Beta = Covariance(Asset, Market) / Variance(Market)',
    example: 'A beta of 1.5 means the stock is 50% more volatile than the market.',
    relatedTerms: ['Alpha', 'Volatility', 'Correlation'],
    category: 'metric',
  },
  {
    id: 'sortino-ratio',
    term: 'Sortino Ratio',
    definition: 'Similar to Sharpe ratio but only considers downside volatility, providing a better measure of risk-adjusted returns for asymmetric return distributions.',
    formula: 'Sortino Ratio = (Portfolio Return - Risk-Free Rate) / Downside Deviation',
    relatedTerms: ['Sharpe Ratio', 'Downside Deviation'],
    category: 'metric',
  },
  {
    id: 'max-drawdown',
    term: 'Maximum Drawdown',
    definition: 'The largest peak-to-trough decline in portfolio value. Measures the worst-case loss an investor would have experienced.',
    example: 'A max drawdown of 20% means the portfolio lost 20% from its highest point.',
    relatedTerms: ['Recovery Time', 'VaR', 'CVaR'],
    category: 'metric',
  },
  {
    id: 'var',
    term: 'VaR (Value at Risk)',
    definition: 'The maximum expected loss over a given time period at a specified confidence level. VaR95 means 95% confidence the loss won\'t exceed this amount.',
    example: 'VaR95 of $10,000 means there\'s a 95% chance daily losses won\'t exceed $10,000.',
    pronunciation: 'vee-ay-ar',
    relatedTerms: ['CVaR', 'Maximum Drawdown'],
    category: 'metric',
  },
  {
    id: 'cvar',
    term: 'CVaR (Conditional Value at Risk)',
    definition: 'The expected loss given that the loss exceeds the VaR threshold. Also called Expected Shortfall.',
    example: 'CVaR95 of $15,000 means when losses exceed VaR95, the average loss is $15,000.',
    pronunciation: 'see-vee-ay-ar',
    relatedTerms: ['VaR', 'Tail Risk'],
    category: 'metric',
  },
  {
    id: 'information-ratio',
    term: 'Information Ratio',
    definition: 'Measures portfolio returns above a benchmark relative to the volatility of those returns. Higher values indicate more consistent outperformance.',
    formula: 'Information Ratio = (Portfolio Return - Benchmark Return) / Tracking Error',
    relatedTerms: ['Alpha', 'Tracking Error', 'Sharpe Ratio'],
    category: 'metric',
  },
  {
    id: 'correlation',
    term: 'Correlation',
    definition: 'A statistical measure of how two variables move together. Ranges from -1 (perfect negative) to +1 (perfect positive).',
    example: 'Correlation of 0.8 between predicted and actual returns indicates strong positive relationship.',
    relatedTerms: ['R-Squared', 'Covariance'],
    category: 'metric',
  },
  {
    id: 'r-squared',
    term: 'R-Squared',
    definition: 'The proportion of variance in the dependent variable explained by the model. Ranges from 0 to 1, with 1 indicating perfect fit.',
    formula: 'R² = 1 - (Sum of Squared Residuals / Total Sum of Squares)',
    example: 'R² of 0.75 means the model explains 75% of the variance in returns.',
    pronunciation: 'ar-squared',
    relatedTerms: ['Correlation', 'MAPE'],
    category: 'metric',
  },

  // Technical Terms
  {
    id: 'ticker',
    term: 'Ticker',
    definition: 'A unique series of letters representing a stock traded on an exchange. B3 tickers typically end with a number (e.g., PETR4, VALE3).',
    example: 'PETR4 represents Petrobras preferred shares on B3.',
    relatedTerms: ['B3', 'Stock'],
    category: 'financial',
  },
  {
    id: 'b3',
    term: 'B3',
    definition: 'Brasil, Bolsa, Balcão - The Brazilian stock exchange where stocks, derivatives, and other securities are traded.',
    pronunciation: 'bay-three',
    relatedTerms: ['Ticker', 'Ibovespa'],
    category: 'financial',
  },
  {
    id: 'ibovespa',
    term: 'Ibovespa',
    definition: 'The main stock market index of B3, representing the performance of the most traded stocks on the Brazilian exchange.',
    pronunciation: 'ee-bo-ves-pa',
    relatedTerms: ['B3', 'Benchmark', 'Index'],
    category: 'financial',
  },
  {
    id: 'ensemble',
    term: 'Ensemble Model',
    definition: 'A deep learning approach that combines predictions from multiple models to improve accuracy and robustness.',
    example: 'The dashboard uses a Transformer+BiLSTM model with attention pooling.',
    relatedTerms: ['Model', 'Prediction', 'Weighting'],
    category: 'dl',
  },
  {
    id: 'shap',
    term: 'SHAP Values',
    definition: 'SHapley Additive exPlanations - A method to explain individual predictions by showing each feature\'s contribution to the final prediction.',
    pronunciation: 'shap',
    example: 'A SHAP value of +0.05 for P/E ratio means this feature increased the prediction by 5%.',
    relatedTerms: ['Feature Importance', 'Explainability'],
    relatedFAQs: ['tech-2'],
    category: 'dl',
  },
  {
    id: 'feature-importance',
    term: 'Feature Importance',
    definition: 'A measure of how much each input feature contributes to model predictions. Higher importance means the feature has more influence.',
    example: 'If price momentum has 25% importance, it\'s the most influential feature in the model.',
    relatedTerms: ['SHAP Values', 'Feature'],
    category: 'dl',
  },
  {
    id: 'confusion-matrix',
    term: 'Confusion Matrix',
    definition: 'A table showing prediction accuracy by comparing predicted vs actual categories. Shows true positives, false positives, true negatives, and false negatives.',
    example: 'A confusion matrix might show the model correctly predicted "up" 80% of the time.',
    relatedTerms: ['Precision', 'Recall', 'Accuracy'],
    relatedFAQs: ['tech-6'],
    category: 'dl',
  },
  {
    id: 'precision',
    term: 'Precision',
    definition: 'The proportion of positive predictions that were correct. Precision = True Positives / (True Positives + False Positives).',
    example: 'Precision of 0.85 for "up" predictions means 85% of predicted ups were actually ups.',
    relatedTerms: ['Recall', 'Accuracy', 'Confusion Matrix'],
    category: 'dl',
  },
  {
    id: 'recall',
    term: 'Recall',
    definition: 'The proportion of actual positives that were correctly identified. Recall = True Positives / (True Positives + False Negatives).',
    example: 'Recall of 0.75 for "up" means the model identified 75% of actual up movements.',
    relatedTerms: ['Precision', 'Accuracy', 'Confusion Matrix'],
    category: 'dl',
  },
  {
    id: 'data-drift',
    term: 'Data Drift',
    definition: 'Changes in the statistical properties of input features over time. Can indicate that training data no longer represents current conditions.',
    example: 'If average P/E ratios shift from 15 to 25, this represents data drift.',
    relatedTerms: ['Concept Drift', 'Distribution', 'KS Test'],
    relatedFAQs: ['d-3'],
    category: 'dl',
  },
  {
    id: 'concept-drift',
    term: 'Concept Drift',
    definition: 'Changes in the relationship between features and target variables. Means model assumptions may no longer hold.',
    example: 'If the correlation between momentum and returns changes from 0.6 to 0.2, this is concept drift.',
    relatedTerms: ['Data Drift', 'Correlation', 'Retraining'],
    relatedFAQs: ['d-4'],
    category: 'dl',
  },
  {
    id: 'ks-test',
    term: 'Kolmogorov-Smirnov Test',
    definition: 'A statistical test that compares two distributions to determine if they differ significantly. Used for drift detection.',
    pronunciation: 'kol-mo-gor-ov smir-nov',
    relatedTerms: ['Data Drift', 'Distribution', 'P-Value'],
    category: 'technical',
  },
  {
    id: 'outlier',
    term: 'Outlier',
    definition: 'A data point that deviates significantly from other observations. Often defined as exceeding 3 standard deviations from the mean.',
    example: 'A prediction error of 50% when most errors are under 5% would be an outlier.',
    relatedTerms: ['Anomaly', 'Standard Deviation'],
    relatedFAQs: ['tech-7'],
    category: 'technical',
  },
  {
    id: 'backtesting',
    term: 'Backtesting',
    definition: 'Simulating a trading strategy using historical data to evaluate its performance. Helps assess strategy viability before live trading.',
    example: 'Backtesting shows the strategy would have returned 15% annually over the past 5 years.',
    relatedTerms: ['Simulation', 'Historical Data', 'Portfolio'],
    relatedFAQs: ['f-7'],
    category: 'financial',
  },
  {
    id: 'rebalancing',
    term: 'Rebalancing',
    definition: 'Adjusting portfolio positions to maintain target allocations or implement new recommendations.',
    example: 'Monthly rebalancing means updating positions once per month based on new recommendations.',
    relatedTerms: ['Portfolio', 'Turnover', 'Transaction Costs'],
    category: 'financial',
  },
  {
    id: 'turnover',
    term: 'Portfolio Turnover',
    definition: 'The rate at which portfolio holdings are replaced. High turnover means frequent trading, which increases costs.',
    formula: 'Turnover = (Total Buys + Total Sells) / 2 / Average Portfolio Value',
    example: 'Annual turnover of 200% means the entire portfolio is replaced twice per year.',
    relatedTerms: ['Rebalancing', 'Transaction Costs'],
    category: 'financial',
  },

  // Infrastructure
  {
    id: 'lambda',
    term: 'AWS Lambda',
    definition: 'A serverless compute service that runs code in response to events. Used for API endpoints and data processing.',
    relatedTerms: ['API Gateway', 'S3', 'Serverless'],
    category: 'infrastructure',
  },
  {
    id: 's3',
    term: 'S3 (Simple Storage Service)',
    definition: 'AWS object storage service used to store data files, model artifacts, and historical records.',
    pronunciation: 'ess-three',
    relatedTerms: ['Lambda', 'Data Lake'],
    category: 'infrastructure',
  },
  {
    id: 'api-gateway',
    term: 'API Gateway',
    definition: 'AWS service that manages API endpoints, handles authentication, rate limiting, and routes requests to Lambda functions.',
    relatedTerms: ['Lambda', 'REST API', 'WebSocket'],
    category: 'infrastructure',
  },
  {
    id: 'elasticache',
    term: 'CloudFront Cache',
    definition: 'AWS CDN service that caches API responses (5 min) and static assets (24h) at edge locations for low-latency access.',
    relatedTerms: ['CDN', 'Cache', 'Performance'],
    category: 'infrastructure',
  },
  {
    id: 'dynamodb',
    term: 'DynamoDB',
    definition: 'AWS NoSQL database service used for storing user preferences, alerts, and configuration data.',
    relatedTerms: ['Database', 'NoSQL'],
    category: 'infrastructure',
  },
  {
    id: 'cloudwatch',
    term: 'CloudWatch',
    definition: 'AWS monitoring and observability service that collects logs, metrics, and events from AWS resources.',
    relatedTerms: ['Monitoring', 'Logs', 'Metrics'],
    category: 'infrastructure',
  },

  // Additional Financial Terms
  {
    id: 'pe-ratio',
    term: 'P/E Ratio',
    definition: 'Price-to-Earnings ratio - A valuation metric comparing stock price to earnings per share. Higher values may indicate overvaluation.',
    formula: 'P/E = Stock Price / Earnings Per Share',
    pronunciation: 'pee-ee ratio',
    example: 'A P/E of 20 means investors pay $20 for every $1 of earnings.',
    relatedTerms: ['P/B Ratio', 'Valuation'],
    category: 'financial',
  },
  {
    id: 'pb-ratio',
    term: 'P/B Ratio',
    definition: 'Price-to-Book ratio - Compares stock price to book value per share. Values below 1 may indicate undervaluation.',
    formula: 'P/B = Stock Price / Book Value Per Share',
    pronunciation: 'pee-bee ratio',
    relatedTerms: ['P/E Ratio', 'Book Value'],
    category: 'financial',
  },
  {
    id: 'roe',
    term: 'ROE (Return on Equity)',
    definition: 'A profitability metric showing how much profit a company generates with shareholders\' equity.',
    formula: 'ROE = Net Income / Shareholders\' Equity',
    pronunciation: 'ar-oh-ee',
    example: 'ROE of 15% means the company generates $0.15 profit for every $1 of equity.',
    relatedTerms: ['ROA', 'Profitability'],
    category: 'financial',
  },
  {
    id: 'dividend-yield',
    term: 'Dividend Yield',
    definition: 'The annual dividend payment as a percentage of stock price. Indicates income return from dividends.',
    formula: 'Dividend Yield = Annual Dividends Per Share / Stock Price',
    example: 'A dividend yield of 5% means $5 annual dividend for every $100 invested.',
    relatedTerms: ['Dividend', 'Income'],
    category: 'financial',
  },
  {
    id: 'market-cap',
    term: 'Market Capitalization',
    definition: 'The total market value of a company\'s outstanding shares. Used to classify company size.',
    formula: 'Market Cap = Stock Price × Total Shares Outstanding',
    example: 'A company with 1 billion shares at $50 each has a $50 billion market cap.',
    relatedTerms: ['Large Cap', 'Small Cap'],
    category: 'financial',
  },
  {
    id: 'volatility',
    term: 'Volatility',
    definition: 'A measure of price fluctuation over time, typically measured as standard deviation of returns. Higher volatility means more risk.',
    example: 'Annual volatility of 20% means returns typically vary by ±20% from the average.',
    relatedTerms: ['Standard Deviation', 'Risk', 'Beta'],
    category: 'financial',
  },
  {
    id: 'momentum',
    term: 'Momentum',
    definition: 'The rate of acceleration of price changes. Stocks with strong momentum tend to continue their trend.',
    example: 'A stock up 20% in 3 months has positive momentum.',
    relatedTerms: ['Trend', 'Technical Analysis'],
    category: 'financial',
  },

  // DL/Data Science Terms
  {
    id: 'transformer-bilstm',
    term: 'Transformer + BiLSTM',
    definition: 'A deep learning architecture combining Transformer Encoder (multi-head self-attention) with Bidirectional LSTM for temporal sequence modeling.',
    pronunciation: 'trans-for-mer bye-el-es-tee-em',
    relatedTerms: ['LightGBM', 'Gradient Boosting', 'Ensemble'],
    category: 'dl',
  },
  {
    id: 'lightgbm',
    term: 'LightGBM',
    definition: 'Light Gradient Boosting Machine - A fast gradient boosting framework that uses tree-based learning algorithms.',
    pronunciation: 'light-gee-bee-em',
    relatedTerms: ['Transformer', 'Gradient Boosting'],
    category: 'dl',
  },
  {
    id: 'neural-network',
    term: 'Neural Network',
    definition: 'A deep learning model inspired by biological neural networks, consisting of interconnected nodes (neurons) organized in layers.',
    relatedTerms: ['Deep Learning', 'Model'],
    category: 'dl',
  },
  {
    id: 'overfitting',
    term: 'Overfitting',
    definition: 'When a model learns training data too well, including noise, resulting in poor performance on new data.',
    example: 'A model with 99% training accuracy but 60% test accuracy is overfitted.',
    relatedTerms: ['Underfitting', 'Generalization', 'Validation'],
    category: 'dl',
  },
  {
    id: 'cross-validation',
    term: 'Cross-Validation',
    definition: 'A technique for assessing model performance by training on different subsets of data and testing on held-out portions.',
    relatedTerms: ['Validation', 'Training', 'Test Set'],
    category: 'dl',
  },
  {
    id: 'hyperparameter',
    term: 'Hyperparameter',
    definition: 'A configuration setting for a deep learning algorithm that must be set before training (e.g., learning rate, tree depth).',
    example: 'Learning rate of 0.001 and d_model of 128 are hyperparameters for the Transformer+BiLSTM.',
    relatedTerms: ['Parameter', 'Tuning'],
    category: 'dl',
  },

  // Dashboard-Specific Terms
  {
    id: 'kpi',
    term: 'KPI (Key Performance Indicator)',
    definition: 'A measurable value that demonstrates how effectively objectives are being achieved. Displayed as cards in the dashboard.',
    pronunciation: 'kay-pee-eye',
    example: 'Total recommendations, average return, and accuracy are KPIs.',
    relatedTerms: ['Metric', 'Dashboard'],
    category: 'technical',
  },
  {
    id: 'filter',
    term: 'Filter',
    definition: 'A user-configurable constraint that limits displayed data based on specific criteria.',
    example: 'Filtering by sector="Technology" shows only tech stocks.',
    relatedTerms: ['Query', 'Search'],
    category: 'technical',
  },
  {
    id: 'drill-down',
    term: 'Drill-Down',
    definition: 'The ability to click on summary data to view detailed information or related data.',
    example: 'Clicking a ticker in the recommendations table opens detailed history and fundamentals.',
    relatedTerms: ['Navigation', 'Detail View'],
    category: 'technical',
  },
  {
    id: 'cross-filter',
    term: 'Cross-Filter',
    definition: 'Applying a filter in one chart or table that automatically filters related visualizations.',
    example: 'Selecting a sector in one chart filters all other charts to show only that sector.',
    relatedTerms: ['Filter', 'Linked Views'],
    category: 'technical',
  },
  {
    id: 'temporal-comparison',
    term: 'Temporal Comparison',
    definition: 'Comparing current metrics against previous time periods to identify trends and changes.',
    example: 'Showing current accuracy of 75% vs previous 70% with +5% change.',
    relatedTerms: ['Time Series', 'Trend'],
    category: 'technical',
  },
  {
    id: 'skeleton-screen',
    term: 'Skeleton Screen',
    definition: 'A loading placeholder that mimics the structure of content being loaded, improving perceived performance.',
    relatedTerms: ['Loading', 'UX'],
    category: 'technical',
  },
  {
    id: 'lazy-loading',
    term: 'Lazy Loading',
    definition: 'A technique that defers loading of non-critical resources until they\'re needed, improving initial load time.',
    example: 'Charts in hidden tabs are only loaded when the tab is activated.',
    relatedTerms: ['Performance', 'Optimization'],
    category: 'technical',
  },
  {
    id: 'websocket',
    term: 'WebSocket',
    definition: 'A communication protocol providing full-duplex communication channels over a single TCP connection, enabling real-time updates.',
    relatedTerms: ['Real-Time', 'API'],
    category: 'technical',
  },
  {
    id: 'cache',
    term: 'Cache',
    definition: 'Temporary storage of frequently accessed data to improve performance and reduce server load.',
    example: 'Recommendation data is cached for 5 minutes to avoid repeated API calls.',
    relatedTerms: ['Performance', 'CloudFront'],
    category: 'technical',
  },
  {
    id: 'aria',
    term: 'ARIA (Accessible Rich Internet Applications)',
    definition: 'A set of attributes that make web content more accessible to people with disabilities, especially when using screen readers.',
    pronunciation: 'air-ee-uh',
    relatedTerms: ['Accessibility', 'WCAG'],
    category: 'technical',
  },
  {
    id: 'wcag',
    term: 'WCAG (Web Content Accessibility Guidelines)',
    definition: 'International standards for making web content accessible to people with disabilities. Level AA is the target compliance level.',
    pronunciation: 'wuh-kag',
    relatedTerms: ['Accessibility', 'ARIA'],
    category: 'technical',
  },
];
